run:
  timeout: 5m
  skip-files:
    - ".*_gen\\.go$"
  tests: false

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/covergates/covergates
  govet:
    check-shadowing: true
    enable-all: true
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - errcheck
    - gocritic
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace

issues:
  exclude:
    - fieldalignment
