run:
  timeout: 5m
  skip-files:
    - ".*_gen\\.go$"
  skip-dirs:
    - testdata


linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/covergates/covergates
  govet:
    check-shadowing: true
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - errcheck
    - gocritic
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
