name: CI

on:
  push:
    branches: [ main ]
    paths:
      - '**.go'
      - 'go.mod'
      - '.golangci.yml'
      - '.github/workflows/ci.yml'
      - '.github/workflows/cd.yml'
  pull_request:
    paths:
      - '**.go'
      - 'go.mod'
      - '.golangci.yml'
      - '.github/workflows/ci.yml'
      - '.github/workflows/cd.yml'

env:
  GOPROXY: "https://proxy.golang.org"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Go Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43
      - name: Frontend Lint
        run: |
          cd web
          npm install
          npm run lint -- --no-fix

  build:
    needs:
      - lint
    name: "${{ matrix.build_types }}"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      BUILD_TYPE: ${{ matrix.build_types }}

    strategy:
      fail-fast: false
      matrix:
        build_types: ["BACKEND", "FRONTEND"]

    services:
      gitea:
        image: blueworrybear/gitea-docker
        ports:
          - 3000:3000

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Golang
        if: env.BUILD_TYPE == 'BACKEND'
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Go Test
        if: env.BUILD_TYPE == 'BACKEND'
        env:
          GITEA_SECRET: ${{ secrets.GITEA_SECRET }}
        run: |
          go test -tags="gitea" -coverprofile=coverage.out ./...

      - name: Go Report
        if: env.BUILD_TYPE == 'BACKEND'
        uses: covergates/github-actions@v1
        with:
          report-id: c6je2rq23akg00c1ran0
          report-type: go
          report-file: ./coverage.out
          pull-request: true

      - name: Setup NPM
        if: env.BUILD_TYPE == 'FRONTEND'
        run: |
          cd web
          npm install

      - name: Frontend Unit Test
        if: env.BUILD_TYPE == 'FRONTEND'
        run: |
          cd web
          npm run test:unit

      - name: Jest Report
        if: env.BUILD_TYPE == 'FRONTEND'
        uses: covergates/github-actions@v1
        with:
          report-id: c6je2rq23akg00c1ran0
          report-type: lcov
          report-file: ./web/coverage/lcov.info
          pull-request: true
